### ISSUE TITLE
do u know why i cannot parse the bar name in this website?

### ISSUE THREAD

**Issue by marcusau** [ruia-plugins/ruia-pyppeteer#2]
domain page: http://barmap.hk/bars?page=1

    class bar_Item(Item):
        target_item = TextField(css_select="div#barmap > div.mdl-layout.mdl-js-layout.is-upgraded > div.mdl-layout__inner-container > div.mdl-layout__content.content > div > div.container > div.mdl-grid > div:nth-child(2)")
                       
        bar_names = TextField(css_select="div#barmap div > a > div > div",many=True)
                                        
   

    class bar_Spider(Spider):
        start_urls = [domain_page]
        concurrency = 1
    

        async def parse(self, response):
            async for item in bar_Item.get_items(html=response.html):
                 yield item

        async def process_item(self, item: bar_Item):
          
            for bar_name in item.bar_names:

                bar=re.sub('\(\'react\-text\: \d{3,4}','',bar_name)
               print(bar)

    if __name__ == '__main__':
        bar_Spider.start()

The feedback is always like this, however, i am 100% the css selector is correct

[2019:03:25 14:21:10] INFO  Spider  Spider started!
[2019:03:25 14:21:10] WARNING Spider  Ruia tried to use loop.add_signal_handler but it is not implemented on this platform.
[2019:03:25 14:21:10] WARNING Spider  Ruia tried to use loop.add_signal_handler but it is not implemented on this platform.
[2019:03:25 14:21:10] INFO  Spider  Worker started: 2196814351352
[2019:03:25 14:21:10] INFO  Spider  Worker started: 2196814351488
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:59602/devtools/browser/6ae3158d-6011-43e1-b076-50d174e5cf84
[I:pyppeteer.launcher] terminate chrome process...
[2019:03:25 14:21:12] ERROR Spider  Extract `div#barmap div > a > div > div` error, please check selector or set parameter named `default`
[2019:03:25 14:21:12] INFO  Spider  Stopping spider: Ruia
[2019:03:25 14:21:12] INFO  Spider  Total requests: 1
[2019:03:25 14:21:12] INFO  Spider  Time usage: 0:00:02.102796
[2019:03:25 14:21:12] INFO  Spider  Spider finished!

**Comment by howie6879** [comment]
I think your extraction rules are wrong.

You can test your rules by using the following code:

```python
import asyncio
from ruia import Item, TextField

from ruia_pyppeteer import PyppeteerRequest as Request


class bar_Item(Item):
    # target_item = TextField(
    #     css_select="div#barmap > div.mdl-layout.mdl-js-layout.is-upgraded > div.mdl-layout__inner-container > div.mdl-layout__content.content > div > div.container > div.mdl-grid > div:nth-child(2)")

    bar_names = TextField(css_select="div#barmap", many=True)


async def test():
    pyppeteer_page_options = {'waitUntil': 'networkidle0'}
    request = Request("http://barmap.hk/bars?page=1", pyppeteer_page_options=pyppeteer_page_options)
    response = await request.fetch()
    item = await bar_Item.get_item(html=response.html)
    print(item.bar_names)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(test())
```

output:
![image](https://user-images.githubusercontent.com/17047388/55042346-ff82dd80-506b-11e9-8533-5a0ed8298010.png)

Absolutely, it can't work by using your rule~

**Comment by marcusau** [comment]
Thanks a lot

> I think your extraction rules are wrong.
> 
> You can test your rules by using the following code:
> 
> ```python
> import asyncio
> from ruia import Item, TextField
> 
> from ruia_pyppeteer import PyppeteerRequest as Request
> 
> 
> class bar_Item(Item):
>     # target_item = TextField(
>     #     css_select="div#barmap > div.mdl-layout.mdl-js-layout.is-upgraded > div.mdl-layout__inner-container > div.mdl-layout__content.content > div > div.container > div.mdl-grid > div:nth-child(2)")
> 
>     bar_names = TextField(css_select="div#barmap", many=True)
> 
> 
> async def test():
>     pyppeteer_page_options = {'waitUntil': 'networkidle0'}
>     request = Request("http://barmap.hk/bars?page=1", pyppeteer_page_options=pyppeteer_page_options)
>     response = await request.fetch()
>     item = await bar_Item.get_item(html=response.html)
>     print(item.bar_names)
> 
> if __name__ == '__main__':
>     asyncio.get_event_loop().run_until_complete(test())
> ```
> 
> output:
> ![image](https://user-images.githubusercontent.com/17047388/55042346-ff82dd80-506b-11e9-8533-5a0ed8298010.png)
> 
> Absolutely, it can't work by using your rule~

Thanks a lot  :)
