### ISSUE TITLE
something wrong with my xpath or my ip has been blocked by the vendor????

### ISSUE THREAD

**Issue by marcusau** [ruia-plugins/ruia-pyppeteer#5]
Hi,

    Thanks for your help.

   I am scrapping the news from this website "https://xueqiu.com/?category=livenews"

  I have double-checked my xpath of the target items and the items i wanna extract but the ruin kept saying my xpath cannot be located.  

  Would you help me check if the problem comes from my ip address (being blocked) or any code mistakes on my ruia spider?

    domain_page = 'https://xueqiu.com/?category=livenews'

    

    class frame_Item(Item):
        target_item = TextField(xpath_select="//body/div[@id='app']/div[@class='AnonymousHome_container_2te']/div[@class='AnonymousHome_home__col--lf_2Fg']/div[@class='AnonymousHome_home__timeline_VTo']/div[2]/div/div")  
        publish_month = TextField(xpath_select="div[@class='div.AnonymousHome_home__timeline-live__hd_JGP']") 

    async def test():
        pyppeteer_page_options = {'waitUntil': 'networkidle2', 'timeout': 0}
        request = Request(domain_page, pyppeteer_page_options=pyppeteer_page_options)
        response = await request.fetch()
        item = await frame_Item.get_item(html=response.html)
        print(item.publish_month)

    if __name__ == '__main__':
       asyncio.get_event_loop().run_until_complete(test())

![image](https://user-images.githubusercontent.com/31444195/63084230-4fabff00-bf7d-11e9-8838-5f17010611e0.png)

**Comment by howie6879** [comment]
Can you find the target field that you need in the `response.html`?

**Comment by marcusau** [comment]
domain_page = 'https://xueqiu.com/?category=livenews'
I have tried but the result is still the same


    class frame_Item(Item):
        target_item = TextField(xpath_select="//body/div[@id='app']/div[@class='AnonymousHome_container_2te']/div[@class='AnonymousHome_home__col--lf_2Fg']/div[@class='AnonymousHome_home__timeline_VTo']/div[2]/div/div")  
        publish_month = TextField(xpath_select="div[@class='div.AnonymousHome_home__timeline-live__hd_JGP']") 



    class realtime_Spider(Spider):
        start_urls = [domain_page]
        concurrency = 1

        async def parse(self, response):
                async for item in frame_Item.get_items(html=response.html):
                    print(item.publish_month)


    if __name__ == '__main__':
       realtime_Spider.start()


![image](https://user-images.githubusercontent.com/31444195/63084561-07d9a780-bf7e-11e9-9650-f4d45134893c.png)

**Comment by howie6879** [comment]
It is obvious, you failed to crawl~ so you need to send a successful request.

2019-08-15 17:02 GMT+08:00, marcusau <notifications@github.com>:

**Comment by marcusau** [comment]
then how to send successful request?

Could u provide some guides for me?

**Comment by howie6879** [comment]
It is depends on your target site., for example: you should send a
HTTP request with some correct parameters and make sure your IP is
available.

2019-08-15 17:08 GMT+08:00, marcusau <notifications@github.com>:

**Comment by marcusau** [comment]
I have checked my IP. It works. and Xpath is also ok too

**Comment by howie6879** [comment]
Maybe the site needs specific parameters but your program doesn't provide
it.

marcusau <notifications@github.com> 于2019年8月15日周四 下午5:19写道：
