### ISSUE TITLE
运行示例 jianshu_js_example.py 报错，‘JianshuSpider’ object has no attribute 'kwargs'

### ISSUE THREAD

**Issue by allanpk716** [ruia-plugins/ruia-pyppeteer#8]
之前用 ruia-pyppeteer 实现了一个爬虫，今天运行的时候报错很诡异，然后尝试新建了一个 pipenv 环境，且跑 jianshu_js_example.py 示例，也会提示 ‘JianshuSpider’ object has no attribute 'kwargs' 类似这样的错误。

貌似 from ruia_pyppeteer import PyppeteerSpider as Spider 继承这个就会出现。

pipenv install 都是自动拉取最新的。

**Comment by howie6879** [comment]
更新最新版，已经修复
